apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-tqjq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-tqjq@sha256:a906b7ffa464fdaabcdf53bb197ba0eacfec5c175c6c85969ecf7eaba5dff432
        name: my-python
        resources: {}
status: {}
